(function(y){function t(){this.icons=[{normal:[23,22],hover:[27,24],normalIamgeCoord:[2,63],hoverIamgeCoord:[32,63]},{normal:[19,17],hover:[23,21],normalIamgeCoord:[3,42],hoverIamgeCoord:[28,42]},{normal:[17,15],hover:[21,19],normalIamgeCoord:[3,22],hoverIamgeCoord:[26,22]},{normal:[15,13],hover:[29,17],normalIamgeCoord:[3,3],hoverIamgeCoord:[24,3]}];soso.maps.Overlay.apply(this,arguments)}function u(a){var b=a.getNorthEast(),c=a.getSouthWest();a=c.getLng();c=c.getLat();var d=b.getLng();b=b.getLat();
var e=(d-a)/2,f=(b-c)/2;a-=e;d+=e;c-=f;b+=f;return new soso.maps.LatLngBounds(new soso.maps.LatLng(c,a),new soso.maps.LatLng(b,d))}function v(a,b){for(var c in b)if(b.hasOwnProperty(c))a.hasOwnProperty(c)||(a[c]=b[c]);return a}function w(a){this.icon={};this._markers={};this.bindsTo(["panorama","planeInfo"],a);this.model=a}function q(a){this.marker=new soso.maps.Marker({clickable:false,draggable:false});this.bindsTo(["map","pov","position"],a)}function r(a){soso.maps.MVCObject.apply(this);var b={map:null,
planeId:null,panorama:null};b=v(b,a);this.setValues(b);this.bgPoi=new w(this)}function j(a,b){b=b||{};b.container=typeof a=="object"?a:document.getElementById(a);b=v(b,{panorama:null,container:null,nolayer:false,visible:true});this.planeMap=new r;this.setValues(b)}var z=[200,200,200,200,300,400,500,600,1E3,3E3,6E3,12E3,25E3,5E4,1E5],i,s=function(a,b,c){b&&(a.style.backgroundImage="url("+b+")");if(c)a.style.backgroundPosition=-c[0]+"px "+-c[1]+"px"},g=t.prototype=new soso.maps.Overlay;g.visible_changed=
function(){this.draw()};g.setVisible=function(a){this.set("visible",a)};g.getVisible=function(){return this.get("visible")};g.setPoi=function(a){this.poi=a;this.draw()};g.construct=function(){var a=document.createElement("div");this.getPanes().overlayShadow.appendChild(a);var b=document.createElement("div");this.get("map");this.getPanes().floatPane.appendChild(b);var c=this;this._hClick=soso.maps.event.addDomListener(b,"click",function(){c._onClick()});this._hMouseOver=soso.maps.event.addDomListener(b,
"mouseover",function(){c._onMouseOver()});this._hMouseOut=soso.maps.event.addDomListener(b,"mouseout",function(){c._onMouseOut()});this._hMouseDown=soso.maps.event.addDomListener(b,"mousedown",function(){c._onMouseDown()});this._hMouseUp=soso.maps.event.addDomListener(b,"mouseup",function(){c._onMouseUp()});this._div=a;this._hitDiv=b};g._resetImageCon=function(){var a=this._div,b=this._getIcon();a.style.cssText="position:absolute;width:"+b.normal[0]+"px;height:"+b.normal[1]+"px;z-index:500;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;";
s(a,"http://api.map.soso.com/plugin/v2/PanoramaOverview/image/camera_region.png",b.normalIamgeCoord);return a};g._resetHitCon=function(){var a=this._getIcon(),b=this._hitDiv;b.style.cssText="position:absolute;width:"+a.normal[0]+"px;height:"+a.normal[1]+"px;background-image:url(about:blank);z-index:700;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;";return b};g._onClick=function(){if(!this.isDragging){this.get("map")._svid=this.poi.svid;var a=this.get("panorama");a&&a.setPano(this.poi.svid)}this.isDragging=
false;if(this._mapDragging){soso.maps.event.removeListener(this._mapDragging);delete this._mapDragging}};g._onMouseDown=function(){var a=this;this.get("map")._svid=this.poi.svid;this._center=this.get("map").getCenter();if(!this._mapDragging)this._mapDragging=soso.maps.event.addListener(this.get("map"),"dragging",function(){var b=a.get("map").getCenter();if(a._center.getLat()!=b.getLat()||a._center.getLng()!=b.getLng())a.isDragging=true})};g._onMouseUp=function(){if(this.isDragging)this.get("map")._svid=
"";else this.get("map")._svid=this.poi.svid;this.isDragging=false;if(this._mapDragging){soso.maps.event.removeListener(this._mapDragging);delete this._mapDragging}};g._onMouseOver=function(){var a=this._getIcon();this._div.style.zIndex="550";this._hitDiv.style.zIndex="750";this._hitDiv.style.width=a.hover[0]+"px";this._div.style.width=a.hover[0]+"px";this._hitDiv.style.height=a.hover[1]+"px";this._div.style.height=a.hover[1]+"px";s(this._div,"http://api.map.soso.com/plugin/v2/PanoramaOverview/image/camera_region.png",
a.hoverIamgeCoord);this._hitDiv.style.top=parseInt(this._hitDiv.style.top)-0+"px";this._hitDiv.style.left=parseInt(this._hitDiv.style.left)-0+"px";this._div.style.top=parseInt(this._div.style.top)-0+"px";this._div.style.left=parseInt(this._div.style.left)-0+"px"};g._onMouseOut=function(){var a=this._getIcon();this._div.style.zIndex="500";this._hitDiv.style.zIndex="700";this._hitDiv.style.width=a.normal[0]+"px";this._hitDiv.style.height=a.normal[1]+"px";this._div.style.width=a.normal[0]+"px";this._div.style.height=
a.normal[1]+"px";this._hitDiv.style.top=parseInt(this._hitDiv.style.top)+0+"px";this._hitDiv.style.left=parseInt(this._hitDiv.style.left)+0+"px";this._div.style.top=parseInt(this._div.style.top)+0+"px";this._div.style.left=parseInt(this._div.style.left)+0+"px";s(this._div,"http://api.map.soso.com/plugin/v2/PanoramaOverview/image/camera_region.png",a.normalIamgeCoord)};g._getIcon=function(){var a=19-this.get("map").getZoom();a=Math.min(a,3);return this.icons[a]};g.destroy=function(){if(this._div){soso.maps.event.removeListener(this._hClick);
soso.maps.event.removeListener(this._hMouseOver);soso.maps.event.removeListener(this._hMouseOut);soso.maps.event.removeListener(this._hMouseDown);soso.maps.event.removeListener(this._hMouseUp);this._div.parentNode.removeChild(this._div);this._hitDiv.parentNode.removeChild(this._hitDiv);this._hitDiv=this._div=null}if(this._mapDragging){soso.maps.event.removeListener(this._mapDragging);delete this._mapDragging}};g.draw=function(){var a=this.get("map");if(this._div&&this.poi&&a){a=this._getIcon();var b=
this.poi,c=this._div.style,d=this._hitDiv.style;this._resetImageCon();this._resetHitCon();d.display=c.display=this.get("visible")?"":"none";var e=this.getProjection().fromLatLngToDivPixel(b.latlng);d.left=c.left=parseInt(e.getX()-a.normal[0]/2)+"px";d.top=c.top=parseInt(e.getY()-a.normal[1]/2)+"px";c.left=c.left=parseInt(e.getX()-a.normal[0]/2)+"px";c.top=c.top=parseInt(e.getY()-a.normal[1]/2)+"px";if(b&&b.n)this._hitDiv.title=b.n;this._hitDiv.svid=b.svid||""}};var x=function(){var a=window._SOSOMapPluginLoader=
{},b=0;return{send:function(c,d){var e="cb"+(new Date).getTime().toString(36)+(b++).toString(36);a[e]=function(l){d&&d(l)};var f=document.createElement("script");f.async="async";f.setAttribute("type","text/javascript");f.setAttribute("charset","gbk");var h=["output=jsonp","fr=mapPlugin","cb=_SOSOMapPluginLoader."+e];h=c+(c.indexOf("?")===-1?"?":"&")+h.join("&");f.src=h;var k=document.head||document.getElementsByTagName("head")[0]||document.documentElement;f.onload=f.onreadystatechange=function(l,
p){if(p||!f.readyState||/loaded|complete/.test(f.readyState)){a[e]=null;f.onload=f.onreadystatechange=null;k&&f.parentNode&&k.removeChild(f);f=undefined}};k.insertBefore(f,k.firstChild)}}}(),m={iconSize:[14,12],map:null,netBounds:[1.23152E-4,1.6093254E-4],level:18,_voidResult:[],voidResult:[],hoverMarkers:{},viewBounds:null,waitQuene:[],inited:false,init:function(a,b){var c=this.netBounds;delete this.hoverMarkers;this.hoverMarkers=[];for(var d=0;d<a.length;d++){var e=a[d],f=this.getIndex(e.latlng,
b,c);this.hoverMarkers[f.col]||(this.hoverMarkers[f.col]=[]);this.hoverMarkers[f.col][f.row]||(this.hoverMarkers[f.col][f.row]=[]);this.hoverMarkers[f.col][f.row].push(e)}this.viewBounds=b;this.inited=true;for(d=0;d<this.waitQuene.length;d++)this.waitQuene[d]&&this.waitQuene[d]()},getIndex:function(a,b,c){var d=a.getLat();a=a.getLng();return{col:Math.floor((a-b[0])/c[1]),row:Math.floor((d-b[1])/c[0])}},getVoidMarkerByBounds:function(a){var b=this._boundsToPoint(a);a=this.netBounds;var c=b[1];b=this.getIndex(b[3],
this.viewBounds,a);c=this.getIndex(c,this.viewBounds,a);var d=b.col>0?b.col:0;a=c.col;b=b.row>0?b.row:0;c=c.row;var e=this.map.getZoom(),f=[],h=[];for(d=d;d<=a;d++)for(var k=b;k<=c;k++)if(this.hoverMarkers[d]&&this.hoverMarkers[d][k])for(var l=0;l<this.hoverMarkers[d][k].length;l++){var p=Math.floor(k/Math.pow(2,this.level-e)),n=Math.floor(d/Math.pow(2,this.level-e));if(!(f[n]&&f[n][p])){f[n]||(f[n]=[]);f[n][p]=this.hoverMarkers[d][k][l];h.push(this.hoverMarkers[d][k][l])}}return h},_boundsToPoint:function(a){var b=
a.getSouthWest().getLng(),c=a.getSouthWest().getLat(),d=a.getNorthEast().getLng(),e=a.getNorthEast().getLat();a=new soso.maps.LatLng(c,b);b=new soso.maps.LatLng(e,b);c=new soso.maps.LatLng(c,d);d=new soso.maps.LatLng(e,d);return[b,d,c,a]}};g=w.prototype=new soso.maps.MVCObject;g.clearCameraMarkers=function(){for(var a in this._markers){this._markers[a].setMap(null);this._markers[a]=null;delete this._markers[a]}this._markers={}};g._renderHoverMarkers=function(a){for(var b=this.get("map"),c={},d=0;d<
a.length;d++){var e=a[d],f;if(this._markers[e.svid]){f=this._markers[e.svid];this._markers[e.svid]=null;delete this._markers[e.svid]}else{f=new t({panorama:this.get("panorama"),visible:true});f.setPoi(e);f.setMap(b)}c[e.svid]=f}for(var h in this._markers){this._markers[h].setMap(null);this._markers[h]=null;delete this._markers[h]}this._markers=c};g._requestPoisByPlaneId=function(){var a=this.get("planeInfo"),b=a.regionId;if(b){b=["http://sv.map.soso.com/rsvids?region_id=",b].join("");var c=this;x.send(b,
function(d){if(c.get("map")&&d&&d.info){d=d.info.svids;var e=[];if(d){for(var f=0;f<d.length;f++){var h=d[f];if(!(parseInt(h.x)==0||parseInt(h.y)==0)){h.x/=111319.49077777778;var k=h,l=h.y/111319.49077777778;l=Math.atan(Math.exp(l*0.017453292519943295))*114.59155902616465-90;k.y=l;h.latlng=o.to(new soso.maps.LatLng(h.y,h.x),0);h.svid=h.id;e.push(h)}}m.init(e,a.bounds)}}})}};g.map_changed=function(){var a=this.get("map");if(m.map=a){if(!this._hMapIdle||!this._hMapMove){this.bindTo("zoom",a);var b=
this;this._hMapIdle=soso.maps.event.addListener(a,"idle",function(){b._onMapIdle()});setTimeout(function(){b._onMapIdle()})}}else{this.unbind("zoom");if(this._hMapIdle){soso.maps.event.removeListener(this._hMapIdle);this._hMapIdle=null}this.clearCameraMarkers()}};g._getBoundsPois=function(){var a=this.get("map");if(a){var b=u(a.getBounds()),c=this;if(m.inited){a=m.getVoidMarkerByBounds(b);c._renderHoverMarkers(a)}else m.waitQuene.push(function(){var d=m.getVoidMarkerByBounds(b);c._renderHoverMarkers(d)})}};
g._onMapIdle=function(){this._getBoundsPois()};g.planeInfo_changed=function(){var a=this.get("planeInfo");try{if(a){this.set("map",this.model.get("map"));var b=a.regionId,c=this.get("planeId");if(b&&c!==b){this.planeId=b;this._requestPoisByPlaneId(b);this.set("planeId",b)}}else this.set("map",null)}catch(d){console.log(d)}};g.zoomLevel_changed=function(){if(m.inited){var a=this.get("map");a=u(a.getBounds());this._renderHoverMarkers(m.getVoidMarkerByBounds(a))}};q.prototype=new soso.maps.MVCObject;
g=q.prototype;g.pov_changed=function(){var a=this.get("pov")||{};if(this.get("pov")){a=this.getScoutIconByHeading(a.heading);a!==this.get("icon")&&this.set("icon",a)}};g.icon_changed=function(){var a=this.get("icon");if(a&&this.marker){this.marker.setIcon(a);a.shape&&this.marker.setShape(a.shape)}};g.position_changed=function(){var a=this.get("position")||null,b=this.get("map");if(b&&b.__convertor)a=b.__convertor.to(a,0);this.marker.setPosition(a)};g.map_changed=function(){this.marker.setMap(this.get("map")||
null)};g.setModel=function(a){this.unbindAll(keyAttr);a?this.bindsTo(keyAttr,a):this.marker.setMap(null)};g.getScoutIconByHeading=function(){var a=new soso.maps.Size(138,96),b=new soso.maps.Point(69,27),c=null;return function(d){if(c==null){c=[];for(var e=0;e<12;e++){var f=new soso.maps.MarkerShape([58,0,80,36],"rect"),h=new soso.maps.MarkerImage("http://s.map.soso.com/themes/default/img/street/3D_People.png?v=v3.3.916",a,new soso.maps.Point(0,e*138+42),b);h.shape=f;c.push(h)}}d||(d=0);if((e=this.get("map"))&&
e.__convertor)d=e.__convertor.headingTo(d);return c[Math.round(d/30)%12]}}();var A={alt:"\u5e73\u9762\u56fe",name:"\u5e73\u9762\u56fe",tileSize:new soso.maps.Size(256,256),getTileUrl:function(a,b){var c=a.x,d=a.y;d=(1<<b+Math.floor(0.5))-1-d;return[i.domain,i.hash,"/",i.regionId,"/",b,"/",Math.floor(c/16),"/",Math.floor(d/16),"/",c,"_",d,".png"].join("")}},o={forwordMatrix:null,backMatrix:null,init:function(a,b){this.isArray(a)||(a=this.to33Arr(a));this.isArray(b)||(b=this.to33Arr(b));this.forwordMatrix=
a;this.backMatrix=b},to:function(a,b){var c=a.getLat(),d=a.getLng(),e=this.forwordMatrix;if(b)e=this.backMatrix;return new soso.maps.LatLng(d*e[1][0]+c*e[1][1]+1*e[1][2],d*e[0][0]+c*e[0][1]+1*e[0][2])},headingTo:function(a){var b=this.forwordMatrix;if(!a&&a!==0||!this.forwordMatrix)return a;a=[Math.sin(a/180*Math.PI),Math.cos(a/180*Math.PI),1];return a=this.getHeading(0,0,a[0]*b[0][0]+a[1]*b[0][1],a[0]*b[1][0]+a[1]*b[1][1])},getHeading:function(a,b,c,d){a={x:c-a,y:d-b};this.normalize(a);b={x:0,y:1};
c=Math.acos(this.dotProduct(a,b))*180/Math.PI;if(this.crossProduct(b,a)>0)c=360-c;return c},dotProduct:function(a,b){return a.x*b.x+a.y*b.y},crossProduct:function(a,b){return a.x*b.y-a.y*b.x},verctorLength:function(a){return Math.sqrt(Math.pow(a.x,2)+Math.pow(a.y,2))},normalize:function(a){var b=this.verctorLength(a);if(b){a.x/=b;a.y/=b}},to33Arr:function(a){a=a.split(",");for(var b=[[],[],[]],c=0,d=0;c<9;c++){c%3==0&&c!==0&&d++;b[d].push(a[c])}return b},isArray:function(a){return"[object Array]"==
Object.prototype.toString.call(a)}};r.prototype=new soso.maps.MVCObject;g=r.prototype;g.panorama_changed=function(){var a=["planeInfo"];this.unbindAll(a);this.get("panorama")&&this.bindsTo(a,this.get("panorama"))};g.map_changed=function(){this.get("map")&&this._resetMap()};g._resetMap=function(){var a=this.get("planeInfo"),b=this.get("map");if(a&&b){i=this.get("planeInfo");a=i.bounds[2];var c=i.bounds[3];a=new soso.maps.LatLngBounds(new soso.maps.LatLng(i.bounds[1],i.bounds[0]),new soso.maps.LatLng(c,
a));i.domain="http://sv0.map.soso.com/rchart/";i.boundary=a;i.hash=i.regionId.split("-")[0];o.init(i.forwardMatrix,i.backwardMatrix);b.setOptions({boundary:a,minZoom:i.minZoom,maxZoom:i.maxZoom,zoomLevel:i.zoomLevel});if(!b.mapTypes.get(i.regionId)){a=new soso.maps.ImageMapType(A);b.mapTypes.set(i.regionId,a)}b.isPlane=true;b.__convertor=o;b.setMapTypeId(i.regionId)}else{if(b){b.setMapTypeId(soso.maps.MapTypeId.ROADMAP);b.setOptions({boundary:null,minZoom:1,maxZoom:18,zoomLevel:15});b.isPlane=false;
b.__convertor=null}i=undefined}};g.planeInfo_changed=function(){var a;return function(){var b=this.get("planeInfo")||{};if(!a||a&&a.regionId!=b.regionId){this._resetMap();a=i}}}();g.convertLatLngToPlane=function(a){return o.to(a,0)};g.convertLatLngToEarth=function(a){return o.to(a,1)};g.planeId_changed=function(){var a=this,b=this.get("planeId");b&&x.send("http://sv.map.soso.com/reginfo?rid="+b,function(c){if(c&&c.detail){c=c.detail;c={regionId:b,bounds:[parseFloat(c.minx),parseFloat(c.miny),parseFloat(c.maxx),
parseFloat(c.maxy)],minZoom:parseInt(c.min_zoom),maxZoom:parseInt(c.max_zoom),zoomLevel:parseInt(c.best_chart_level||0),forwardMatrix:c.forward_matrix||"",center:new soso.maps.LatLng(parseFloat(c.centery),parseFloat(c.centerx)),backwardMatrix:c.backward_matrix||""};a.set("planeInfo",c)}})};j.prototype=new soso.maps.MVCObject;j.prototype.notifyResize=function(){soso.maps.event.trigger(this,"resize")};j.prototype.getMap=function(){return this.get("map")};j.prototype.setContainer=function(a){this.set("container",
a);this.draw()};j.prototype.planeInfo_changed=function(){if(this.get("planeInfo")){this.set("pov",this.get("pov"));this.panoramaLayer&&this.panoramaLayer.setMap(null)}else this.get("nolayer")||this.panoramaLayer&&this.get("map")&&this.panoramaLayer.setMap(this.get("map"))};j.prototype.nolayer_changed=function(){if(!this.get("nolayer")){this.panoramaLayer||this._createLayer();this.get("map")&&this.panoramaLayer.setMap(this.get("map"))}this.panoramaLayer&&this.get("nolayer")&&this.panoramaLayer.setMap(null)};
j.prototype.setPanorama=function(a){this.set("panorama",a);this.draw();this.planeMap.set("panorama",a)};j.prototype.draw=function(){var a=this.get("container"),b=this.get("panorama");if(a&&b){this._createMap();this._initMapListener();this._createLayer();this._createScout();this._bindsToPanorama()}else this.destroy()};j.prototype._createMap=function(){var a=this.get("map"),b=this.get("position"),c=this.get("container");if(c){var d=document.createElement("div");c.appendChild(d);d.style.cssText="width:100%;height:100%;position:relative;";
this.set("mapCon",d);if(!a){a=new soso.maps.Map(d,{__hideLogo__:true,draggableCursor:"pointer",isMini:true,minZoom:4,maxZoom:18,zoom:15});this.set("map",a);this.planeMap.set("map",a)}b&&a.panoTo(b)}};j.prototype._initMapListener=function(){var a=this.get("map"),b=this;soso.maps.event.addListener(a,"click",function(c){c=c.latLng;if(a&&a.__convertor)c=a.__convertor.to(c,1);if(c){var d=a.getZoom();b._goTo(c,z[18-d])}})};j.prototype.removePanoLayer=function(){this.set("nolayer",true)};j.prototype.showPanoLayer=
function(){this.set("nolayer",false)};j.prototype._createLayer=function(){if(!this.get("nolayer")){if(!this.panoramaLayer)this.panoramaLayer=new soso.maps.PanoramaLayer;this.get("map")&&this.panoramaLayer.setMap(this.get("map"))}};j.prototype._createScout=function(){if(!this.scout)this.scout=new q(this)};j.prototype._goTo=function(a,b){var c=this;if(!this.panoramaService)this.panoramaService=new soso.maps.PanoramaService;this.panoramaService.getPano(a,b,function(d){if(d&&d.svid){var e=c.get("panorama");
e&&e.setPano(d.svid)}})};j.prototype.destroy=function(){this.unbindAll(["pov","position"]);if(this.scout){this.scout.setModel(null);delete this.scout}this.get("mapCon");this.set("mapCon",null);this.set("map",null)};j.prototype._bindsToPanorama=function(){var a=this.get("panorama"),b=["pov","position","planeInfo"];this.unbindAll(b);a&&this.bindsTo(b,a)};j.prototype.position_changed=function(){var a=this.get("position"),b=this.get("map");if(a&&a.lat&&a.lng&&b){if(b&&b.__convertor)a=b.__convertor.to(a,
0);b.panTo(a)}};y.PanoOverview=j})(soso.maps);
